
default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling

development:
  <<: *default
  database: pitchupp