# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a192fd435a4e471b2cf3fa0b1f858f18c284dde41131009be7481987f75010f8c1b14e9fd08fb1c89aaa18493a6d785a0d189d84e262c0bcd9527561b13496a7

test:
  secret_key_base: ffdee37f7294e3c5ac48127c1f1386cee3655388812906cf7dd0aeea193ec85dacfc77a64f2b4d65234c6e511bd43af2463b43165e8dbbdec393f69b7df73e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
